### ISSUE TITLE
Support GNOME 44

### ISSUE THREAD

**Issue by Cryolitia** [tuberry/desktop-lyric#16]
![image](https://github.com/tuberry/desktop-lyric/assets/23723294/02cf840e-856f-431f-97ba-cd087e98af08)
There're many software repositories update to gnome 44 but not 45, such as nixos-unstable, please consider them.

**Comment by tuberry** [comment]
Sorry, version 44 uploaded to ego was rejected by reviewers due to code style. Actually, there's no breaking changes from version 43. Now that Gnome 45 has been released, version 44 will not be supported. If you're using `nixos-unstable`, I'd recommend just modifying the metadata.json `version` from 43 to 44 under the extension's directory for now.
